{
 "title": "Pino HTTP Logs",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {}
   },
   { "name": "status", "label": "Status Code", "query": "200,201,401,404,500, " },
   {
    "name": "level",
    "label": "Log Level",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    count_over_time(\n        {service=~\"$service\"} \n        |= \"request completed\"\n        | json\n        | res.statusCode >= 0\n        [${__range}]\n    )\n)",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Success Requests 2xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    count_over_time(\n        {service=~\"$service\"} \n        |= \"request completed\"\n        | json\n        | res.statusCode >= 200 and res.statusCode < 400\n        [${__range}]\n    )\n)",
     "legendFormat": "2xx"
    }
   ]
  },
  {
   "title": "Bad Requests 4xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    count_over_time(\n        {service=~\"$service\"} \n        |= \"request completed\"\n        | json\n        | res.statusCode >= 400 and res.statusCode < 500\n        [${__range}]\n    )\n)",
     "legendFormat": "4xx"
    }
   ]
  },
  {
   "title": "Errored Requests 5xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    count_over_time(\n        {service=~\"$service\"} \n        |= \"request completed\"\n        | json\n        | res.statusCode >= 500\n        [${__range}]\n    )\n)",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Requests by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count_over_time(\n    {service=~\"$service\"} \n    |= \"request completed\"\n    | json\n    | label_format status=\"{{res.statusCode}}\"\n    [1m]\n)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "App Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{service=~\"$service\", level=~\"$level\"}\n| json\n| res.statusCode=~\"$status\""
    }
   ]
  }
 ]
}